/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EinkauflisteApp;

import org.junit.Test;
import static org.junit.Assert.*;


public class EintraegeTest {
	
	Eintraege eintrag = new Eintraege("Eier", "1");
	
    @Test 
    public void testConstructor() {
        assertNotNull(eintrag);
    }
    
    @Test 
    public void testSetBezeichner() {
        eintrag.setBezeichner("Brot");
        assertEquals("Brot",eintrag.getBezeichner());
    }
    
    @Test 
    public void testSetMenge() {
        eintrag.setMenge("7");
        assertEquals("7",eintrag.getMenge());
    }
}
