/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EinkauflisteApp;

import org.junit.Test;
import static org.junit.Assert.*;

public class EintraegeTest {
    @Test public void testConstructor() {
        Eintraege eintrag = new Eintraege("Eier", 1);
        assertNotNull(eintrag);
    }
}
