/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EinkauflisteApp;

import java.io.Serializable;

/**
 * @author Fabian Seelert
 * 
 * Diese Klasse baut die Einträge in der Einkaufsliste
 *
 */
public class Eintraege implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -3966271017527959798L;
	private String bezeichner;
	private String menge;
	/**
	 * Konstruktor
	 * 
	 * @param bezeichner Der Bezeichner des Produkts
	 * @param menge Die benötigte Menge
	 */
	public Eintraege(String bezeichner, String menge) {
		this.bezeichner = bezeichner;
		this.menge = menge;
	}

	public void setBezeichner(String bezeichner) {
		this.bezeichner = bezeichner;
	}
	
	
	public String getBezeichner() {
		return bezeichner;
	}
	
	public void setMenge (String menge) {
		this.menge = menge;
	}
	
	public String getMenge() {
		return menge;
	}
}
