/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EinkauflisteApp;


/**
 * @author Fabian Seelert
 * 
 * Diese Klasse baut die Einträge in der Einkaufsliste
 *
 */
public class Eintraege {

	private String bezeichner;
	private int menge;
	/**
	 * Konstruktor
	 * 
	 * @param bezeichner Der Bezeichner des Produkts
	 * @param menge Die benötigte Menge
	 */
	public Eintraege(String bezeichner, int menge) {
		this.bezeichner = bezeichner;
		this.menge = menge;
	}

	public void setBezeichner(String bezeichner) {
		this.bezeichner = bezeichner;
	}
	
	
	public String getBezeichner() {
		return bezeichner;
	}
	
	public void setMenge (int menge) {
		this.menge = menge;
	}
	
	public int getMenge() {
		return menge;
	}
}
